# General Parameters
use_scan_matching: false
use_scan_barycenter: false
minimum_travel_distance: 0.12 
minimum_travel_heading: 0.174             #in radians
scan_buffer_size: 20
scan_buffer_maximum_scan_distance: 3.5
link_match_minimum_response_fine: 0.12
link_scan_maximum_distance: 3.5
loop_search_maximum_distance: 3.5
do_loop_closing: true
loop_match_minimum_chain_size: 10
loop_match_maximum_variance_coarse: 0.4   # gets squared later
loop_match_minimum_response_coarse: 0.8
loop_match_minimum_response_fine: 0.8

# Correlation Parameters - Correlation Parameters
correlation_search_space_dimension: 0.3
correlation_search_space_resolution: 0.01
correlation_search_space_smear_deviation: 0.03

# Correlation Parameters - Loop Closure Parameters
loop_search_space_dimension: 8.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.03

# Scan Matcher Parameters
distance_variance_penalty: 990.3      # gets squared later
angle_variance_penalty: 990.349       # in degrees (gets converted to radians then squared)
fine_search_angle_offset: 990.00349   # in degrees (gets converted to radians)
coarse_search_angle_offset: 990.349   # in degrees (gets converted to radians)
coarse_angle_resolution: 990.0349     # in degrees (gets converted to radians)
minimum_angle_penalty: 990.9
minimum_distance_penalty: 990.5
use_response_expansion: false
